#macro RIGHT 0
#macro UP 1
#macro LEFT 2
#macro DOWN 3
#macro HELMET item_type.helmet
#macro CHESTPLATE item_type.chestplate
#macro LEGGINGS item_type.leggings
#macro BOOTS item_type.boots
#macro RING item_type.ring
#macro MELEEWEAPON item_type.meleeweapon
#macro RANGEDWEAPON item_type.rangedweapon
#macro WEAPONSLOT global.armor_equipped[6,0]