#macro RIGHT 0
#macro UP 1
#macro LEFT 2
#macro DOWN 3
#macro MOVE 0
#macro ATTACK 1
#macro IDLE 2
#macro HELMET item_type.helmet
#macro CHESTPLATE item_type.chestplate
#macro LEGGINGS item_type.leggings
#macro BOOTS item_type.boots
#macro RING item_type.ring
#macro WEAPON item_type.weapon
