ini_open("game_settings.ini")
ini_write_real("settings", "soundvolume", global.soundvolume)
ini_write_real("settings", "musicvolume", global.musicvolume)
ini_write_real("settings", "mastervolume", global.mastervolume)
ini_write_real("settings", "width", global.width)
ini_write_real("settings", "height", global.height)
ini_write_real("settings", "guisize", global.guisize)
ini_write_real("settings", "fullscreen", global.fullscreen)
ini_write_string("settings","language",global.language)
ini_write_real("keys","key_up",global.key_up)
ini_write_real("keys","key_down",global.key_down)
ini_write_real("keys","key_left",global.key_left)
ini_write_real("keys","key_right",global.key_right)
ini_write_real("keys","inventory_hotkey1",global.inventory_hotkey1)
ini_write_real("keys","inventory_hotkey2",global.inventory_hotkey2)
ini_write_real("keys","inventory_hotkey3",global.inventory_hotkey3)
ini_write_real("keys","inventory_hotkey4",global.inventory_hotkey4)
ini_write_real("keys","inventory_hotkey5",global.inventory_hotkey5)
ini_write_real("keys","inventory_hotkey6",global.inventory_hotkey6)
ini_write_real("keys","inventory_hotkey7",global.inventory_hotkey7)
ini_write_real("keys","inventory_hotkey8",global.inventory_hotkey8)
ini_write_real("keys","inventory_hotkey9",global.inventory_hotkey9)
ini_write_real("keys","inventory_hotkey10",global.inventory_hotkey10)
ini_write_real("keys","pickup_key",global.pickup_key)
ini_write_real("keys","interact_key",global.interact_key)
ini_write_real("keys","attack_key",global.attack_key)
ini_write_real("keys","inventory_key",global.inventory_key)
ini_write_real("keys","drop_item_key",global.drop_item_key)
ini_write_real("keys","combination_key",global.combination_key)
ini_write_real("keys","pause_key",global.pause_key)
ini_write_real("keys","developer_key",global.developer_key)
ini_close()